// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Db7nCi0PztVHIwy1u4HNvoLZ1YOoILg',
    appId: '1:39979465391:web:c66169db13741fed47b25a',
    messagingSenderId: '39979465391',
    projectId: 'iburgerfirebase',
    authDomain: 'iburgerfirebase.firebaseapp.com',
    storageBucket: 'iburgerfirebase.appspot.com',
    measurementId: 'G-QT1WTQ0VK6',
    databaseURL: 'https://iburgerfirebase-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFvSAtbEpKGZsODiCXripviGIIMs0GKfk',
    appId: '1:39979465391:android:2a64705f0511ee7947b25a',
    messagingSenderId: '39979465391',
    projectId: 'iburgerfirebase',
    storageBucket: 'iburgerfirebase.appspot.com',
    databaseURL: 'https://iburgerfirebase-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOooSU7ojcY4K0v_tvIPyrF1IvDyUWjU',
    appId: '1:39979465391:ios:3c6323c68919d90347b25a',
    messagingSenderId: '39979465391',
    projectId: 'iburgerfirebase',
    storageBucket: 'iburgerfirebase.appspot.com',
    iosBundleId: 'com.example.iburger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtOooSU7ojcY4K0v_tvIPyrF1IvDyUWjU',
    appId: '1:39979465391:ios:3c6323c68919d90347b25a',
    messagingSenderId: '39979465391',
    projectId: 'iburgerfirebase',
    storageBucket: 'iburgerfirebase.appspot.com',
    iosBundleId: 'com.example.iburger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Db7nCi0PztVHIwy1u4HNvoLZ1YOoILg',
    appId: '1:39979465391:web:d578f083af16d40447b25a',
    messagingSenderId: '39979465391',
    projectId: 'iburgerfirebase',
    authDomain: 'iburgerfirebase.firebaseapp.com',
    storageBucket: 'iburgerfirebase.appspot.com',
    measurementId: 'G-2YFXFPKB4N',
    databaseURL: 'https://iburgerfirebase-default-rtdb.firebaseio.com/',
  );
}
